### ISSUE TITLE
Prefer bottom margin

### ISSUE THREAD

**Issue by DanWebb** [etchteam/stylelint#14]
Top and bottom margins can combine causing unexpected results.

Where only one margin is applied we should prefer bottom margin over top, because pages read downwards.

**Comment by DanWebb** [comment]
I'm not sure this can be implemented as a lint rule, it might need to be added as an additional style guide maybe in the readme

**Comment by JoshTheWanderer** [comment]
@DanWebb I've moved this over here, as it seems a better fit. It looks like it needs a custom plugin, I haven't found anything off the shelf that'll do the job.

**Comment by DanWebb** [comment]
@JoshTheWanderer Actually, I find it happening mostly with the spacing component.

Inner component spacing isn't as much of a concern, because the top/bottom margin issue isn't a result of unexpected component combinations.

If it can't be a lint rule, maybe as simple as a comment on the `top` prop of the spacing component would do the trick.

**Comment by JoshTheWanderer** [comment]
Maybe we could remove that prop as a breaking change?

**Comment by DanWebb** [comment]
Yeah, maybe, I hadn't considered that maybe top isn't needed at all, I can't think of any use cases right now
